title: 'Theme Settings'
data:
  template: v1
  google_font:
    code: |-
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    mode: htmlmixed
  primary: '#325ced'
  secondary: '#bccaef'
  tertiary: '#eff4fe'
  quaternary: '#f9f9f9'
  white: '#ffffff'
  lightGrey: '#c8c7cc'
  darkGrey: '#666666'
  black: '#000000'
